[2024-12-01T15:50:04.464+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 manual__2024-12-01T15:49:59.696862+00:00 [queued]>
[2024-12-01T15:50:04.475+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 manual__2024-12-01T15:49:59.696862+00:00 [queued]>
[2024-12-01T15:50:04.476+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-12-01T15:50:04.476+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-12-01T15:50:04.476+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-12-01T15:50:04.491+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2024-12-01 15:49:59.696862+00:00
[2024-12-01T15:50:04.496+0000] {standard_task_runner.py:55} INFO - Started process 430 to run task
[2024-12-01T15:50:04.499+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'tsk4', 'manual__2024-12-01T15:49:59.696862+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmpkdirlsbm']
[2024-12-01T15:50:04.499+0000] {standard_task_runner.py:83} INFO - Job 173: Subtask tsk4
[2024-12-01T15:50:04.559+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.tsk4 manual__2024-12-01T15:49:59.696862+00:00 [running]> on host 6e7845de4fa8
[2024-12-01T15:50:04.637+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=marciothadeu1984@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2024-12-01T15:49:59.696862+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-01T15:49:59.696862+00:00
[2024-12-01T15:50:04.638+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-01T15:50:04.639+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-12-01T15:50:04.650+0000] {subprocess.py:86} INFO - Output:
[2024-12-01T15:50:04.651+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-01T15:50:04.664+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-01T15:50:04.667+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_test, task_id=tsk4, execution_date=20241201T154959, start_date=20241201T155004, end_date=20241201T155004
[2024-12-01T15:50:04.684+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 173 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 430)
[2024-12-01T15:50:04.710+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-12-01T15:50:04.739+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
