[2024-11-23T16:37:00.563+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag3.tsk2 manual__2024-11-23T16:37:00.067942+00:00 [queued]>
[2024-11-23T16:37:00.574+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag3.tsk2 manual__2024-11-23T16:37:00.067942+00:00 [queued]>
[2024-11-23T16:37:00.574+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-23T16:37:00.575+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-11-23T16:37:00.575+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-23T16:37:00.594+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk2> on 2024-11-23 16:37:00.067942+00:00
[2024-11-23T16:37:00.600+0000] {standard_task_runner.py:55} INFO - Started process 21727 to run task
[2024-11-23T16:37:00.604+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerdag3', 'tsk2', 'manual__2024-11-23T16:37:00.067942+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/triggerDag3.py', '--cfg-path', '/tmp/tmphdrrcrjn']
[2024-11-23T16:37:00.605+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask tsk2
[2024-11-23T16:37:00.673+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerdag3.tsk2 manual__2024-11-23T16:37:00.067942+00:00 [running]> on host 6b6513c1cd28
[2024-11-23T16:37:00.758+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerdag3
AIRFLOW_CTX_TASK_ID=tsk2
AIRFLOW_CTX_EXECUTION_DATE=2024-11-23T16:37:00.067942+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-23T16:37:00.067942+00:00
[2024-11-23T16:37:00.758+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-11-23T16:37:00.759+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-11-23T16:37:00.773+0000] {subprocess.py:86} INFO - Output:
[2024-11-23T16:37:00.775+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-23T16:37:00.788+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-23T16:37:00.792+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=triggerdag3, task_id=tsk2, execution_date=20241123T163700, start_date=20241123T163700, end_date=20241123T163700
[2024-11-23T16:37:00.806+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 45 for task tsk2 (Bash command failed. The command returned a non-zero exit code 1.; 21727)
[2024-11-23T16:37:00.815+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-23T16:37:00.840+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
